package vn.hoicon.rules

import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Shared vectors `docs/schemas/fixtures/h1_vectors.json` (ADR-006): the device and the backend must agree on
 * E.164 normalisation and h1 byte-for-byte. Fixture is generated by `scripts/fixtures/gen_h1_vectors.mjs`.
 */
class PhoneHasherVectorsTest {
    private data class Vector(val input: String, val e164: String?, val h1: String?, val last3: String?)

    private val vectors: List<Vector> by lazy {
        val path = assertNotNull(System.getProperty("hoicon.h1Vectors"), "vector path not set by Gradle")
        val json = File(path).readText()
        val field = """(null|"((?:[^"\\]|\\.)*)")"""
        Regex(""""input":\s*"((?:[^"\\]|\\.)*)",\s*"e164":\s*$field,\s*"h1":\s*$field,\s*"last3":\s*$field""")
            .findAll(json)
            .map { m ->
                fun opt(i: Int) = if (m.groupValues[i] == "null") null else m.groupValues[i + 1]
                Vector(input = m.groupValues[1], e164 = opt(2), h1 = opt(4), last3 = opt(6))
            }.toList()
    }

    @Test
    fun fixtureIsNotEmpty() = assertTrue(vectors.size >= 10, "expected ≥ 10 vectors, got ${vectors.size}")

    @Test
    fun normalisationMatchesVectors() {
        for (v in vectors) assertEquals(v.e164, PhoneHasher.toE164(v.input), "toE164 for vector '${v.input}'")
    }

    @Test
    fun hashAndLast3MatchVectors() {
        for (v in vectors) {
            val hashed = PhoneHasher.hash(v.input)
            assertEquals(v.h1, hashed?.h1, "h1 for vector '${v.input}'")
            assertEquals(v.last3, hashed?.last3, "last3 for vector '${v.input}'")
        }
    }
}
